kafka:
  servers:
    - kafka://localhost:9092

mongo:
  host: localhost
  port: 20017
  database: horton
  username: admin
  password: admin_password

service:
  apiendpoint: https://www.alphavantage.co/
  apikey: <token>
